''''Psuedocode'''

'''IMPORT RANDOM

1. print welcoming message
2. Get LEN() of mystery word generated by computer 
3. print number of spaces for random mystery
word
4. Get LEN() of mystery word generated by computer 
5. Display Live/Tries count starting at 0,
it'll decrease with each incorrect guess
6. Create WHILE LOOP that keeps game going 
as long as spider isn't fully built or life/try
count isn't breached. 
7. FOR LOOP nested within WHILE LOOP to react to wrong and correct guesses  '''